## -----------------------------
## Base (comum a todos: dongle + left + right)
## -----------------------------

# Identidade base (os nomes BLE específicos já vão no build.yaml)
CONFIG_ZMK_KEYBOARD_NAME="Sofle"

# BLE base
CONFIG_ZMK_BLE=y
CONFIG_BT=y

# Split base (papéis central/peripheral ficam no build.yaml)
CONFIG_ZMK_SPLIT=y

# Power
CONFIG_ZMK_PM_SOFT_OFF=y

# Hardware removido
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n

# IMPORTANTE: não forçar USB/Studio/EC11 aqui
# CONFIG_ZMK_USB=...
# CONFIG_USB=...
# CONFIG_ZMK_STUDIO=...
# CONFIG_EC11=...
