manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cormoran
      url-base: https://github.com/cormoran

  projects:
    # ZMK com suporte de "custom studio protocol" (requisito do módulo)
    - name: zmk
      remote: cormoran
      revision: v0.3+custom-studio-protocol
      import: file: app/west.yml

    # Módulo: runtime-configurable sensor rotate + Studio RPC
    - name: zmk-behavior-runtime-sensor-rotate
      remote: cormoran
      revision: main

  self:
    path: config
